In [1]:
# Numpy is a library for performing advanced mathematical operations on Arrays
# import the pandas library:
# Pandas is a powerful library to read and process data tables
import numpy as np
# it means that we can use abbreviation "np" from now on to refer to numpy functions 
import pandas as pd

In [2]:
##Step1: Importing the sklearn class (machine learning algorithm) that you would like to use for modeling:
# The following lines will import LogisticRegression, KNeighborsClassifier "Class" and DecisionTreeClassifier Classes
# "LogisticRegression" and "DecisionTreeClassifier" are the names of a "sklearn classes" to perform Logistic Regression and Decision Tree based Classification
# KNeighborsClassifier is name of a "sklearn class" to perform "KNN Classification"

In [3]:
# loading a CSV file from local device and store it in a pandas DataFrame:
# "read_csv" is a pandas function to read csv files from web or local device:

df = pd.DataFrame()
NDF = pd.DataFrame()

df = pd.read_csv('/Users/cherylmariajose/Desktop/cs4661/project/train.csv')

In [4]:
df

       S1  C1  S2  C2  S3  C3  S4  C4  S5  C5  hand
0       4   9   2   1   2   2   4   7   2   8     0
1       1   4   3   6   1  12   3  11   2   7     0
2       1  11   4   1   3   7   4  11   2   1     2
3       2   9   2   4   3   6   1   9   4   9     3
4       1   8   2   4   2  11   2   2   2   1     0
5       2   5   1   5   2  13   2   3   3  13     2
6       3  10   4   6   1   4   2  13   4   5     0
7       4  10   3   1   2  13   4   2   4   7     0
8       3   2   4  10   3   3   4   4   1   9     0
9       2   7   3   8   4   8   2  13   2  12     1
10      2   5   1   3   2  10   3   2   2   1     0
11      1   6   2  12   4   7   2  10   1   1     0
12      4   2   4   9   1  12   3   7   2  11     0
13      2   6   1   5   3   3   4   2   4   5     1
14      1   6   3  12   4  11   2  11   3  13     1
15      2   5   2   4   4   9   2   3   3   2     0
16      4   9   4  11   3   8   3   9   3   5     1
17      1   9   2   4   1  11   3   4   1  13     1
18      1  11   3  13   4   8   4   1   3   6     0
19      2   6   1  12   3   8   4   1   4   6     1
20      2   9   3   7   1  13   2  13   1   2     1
21      4   4   2  13   3   6   2   7   3   3     0
22      3   6   1   4   3   1   2   5   4   9     0
23      1   4   4   3   2  11   4  13   1  10     0
24      3   9   2   7   2   4   2   1   1  10     0
25      2   4   4   2   1   4   4   1   3  11     1
26      2   8   1   4   3  11   1   8   1   2     1
27      3   8   1  12   4   1   4  10   1   3     0
28      2  12   1   5   1   2   1  10   2   8     0
29      2   4   4   7   4   2   4  11   2   2     1
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..   ...
24980   2   5   4  13   1   3   4   8   3   9     0
24981   3   7   4  11   3   1   1  13   4   3     0
24982   4  10   2   3   1   8   3  11   2   7     0
24983   1   5   2   6   3  10   4  10   3   3     1
24984   4  10   2   5   4   6   2  10   3  12     1
24985   2   6   2   7   4   2   3   6   3   9     1
24986   1   7   2   4   2   1   1   1   2  11     1
24987   3   8   4  10   3   2   4   6   1  11     0
24988   2   8   4   8   1   3   3   8   1   5     3
24989   1   1   1   7   3   9   4   9   1   5     1
24990   4   2   3   7   1  13   2  12   2   9     0
24991   1   7   3  10   3  13   1  13   4  10     2
24992   1  10   4   5   1   6   3   7   2   5     1
24993   3   4   3   3   4  10   2   1   4   6     0
24994   4   1   3   2   2  11   2   6   2   3     0
24995   3   3   4   5   3   4   4   4   1   3     2
24996   3   7   1  13   1   2   1   9   2  11     0
24997   2  13   1   5   4   5   4   8   3   3     1
24998   3   2   4  10   2   6   1  12   3  10     1
24999   1   8   4   2   3   1   1   5   1  10     0
25000   4   4   1  10   3  11   2   2   3   8     0
25001   2  12   4   9   4  10   3  13   3   9     1
25002   1  12   2  13   4   2   1   8   2  10     0
25003   2   3   1   9   1   1   3   8   3   7     0
25004   3   4   2   8   4   8   1   9   2  11     1
25005   4   9   4   6   3   6   4  12   4   5     1
25006   3   8   3   5   4  11   2   2   1  13     0
25007   1   8   4   5   3  11   3   2   2  13     0
25008   4  12   3   5   2   1   2   7   4   6     0
25009   1   1   1   3   1   7   1   2   4   2     1

[25010 rows x 11 columns]

In [7]:
# Creating the Feature Matrix for iris dataset:

# create a python list of feature names that would like to pick from the dataset:
feature_col = ['S1','C1','S2','C2','S3','C3','S4','C4','S5','C5']

# use the above list to select the features from the original DataFrame
X = df[feature_col]  

# print the first 5 rows
X

       S1  C1  S2  C2  S3  C3  S4  C4  S5  C5
0       4   9   2   1   2   2   4   7   2   8
1       1   4   3   6   1  12   3  11   2   7
2       1  11   4   1   3   7   4  11   2   1
3       2   9   2   4   3   6   1   9   4   9
4       1   8   2   4   2  11   2   2   2   1
5       2   5   1   5   2  13   2   3   3  13
6       3  10   4   6   1   4   2  13   4   5
7       4  10   3   1   2  13   4   2   4   7
8       3   2   4  10   3   3   4   4   1   9
9       2   7   3   8   4   8   2  13   2  12
10      2   5   1   3   2  10   3   2   2   1
11      1   6   2  12   4   7   2  10   1   1
12      4   2   4   9   1  12   3   7   2  11
13      2   6   1   5   3   3   4   2   4   5
14      1   6   3  12   4  11   2  11   3  13
15      2   5   2   4   4   9   2   3   3   2
16      4   9   4  11   3   8   3   9   3   5
17      1   9   2   4   1  11   3   4   1  13
18      1  11   3  13   4   8   4   1   3   6
19      2   6   1  12   3   8   4   1   4   6
20      2   9   3   7   1  13   2  13   1   2
21      4   4   2  13   3   6   2   7   3   3
22      3   6   1   4   3   1   2   5   4   9
23      1   4   4   3   2  11   4  13   1  10
24      3   9   2   7   2   4   2   1   1  10
25      2   4   4   2   1   4   4   1   3  11
26      2   8   1   4   3  11   1   8   1   2
27      3   8   1  12   4   1   4  10   1   3
28      2  12   1   5   1   2   1  10   2   8
29      2   4   4   7   4   2   4  11   2   2
...    ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
24980   2   5   4  13   1   3   4   8   3   9
24981   3   7   4  11   3   1   1  13   4   3
24982   4  10   2   3   1   8   3  11   2   7
24983   1   5   2   6   3  10   4  10   3   3
24984   4  10   2   5   4   6   2  10   3  12
24985   2   6   2   7   4   2   3   6   3   9
24986   1   7   2   4   2   1   1   1   2  11
24987   3   8   4  10   3   2   4   6   1  11
24988   2   8   4   8   1   3   3   8   1   5
24989   1   1   1   7   3   9   4   9   1   5
24990   4   2   3   7   1  13   2  12   2   9
24991   1   7   3  10   3  13   1  13   4  10
24992   1  10   4   5   1   6   3   7   2   5
24993   3   4   3   3   4  10   2   1   4   6
24994   4   1   3   2   2  11   2   6   2   3
24995   3   3   4   5   3   4   4   4   1   3
24996   3   7   1  13   1   2   1   9   2  11
24997   2  13   1   5   4   5   4   8   3   3
24998   3   2   4  10   2   6   1  12   3  10
24999   1   8   4   2   3   1   1   5   1  10
25000   4   4   1  10   3  11   2   2   3   8
25001   2  12   4   9   4  10   3  13   3   9
25002   1  12   2  13   4   2   1   8   2  10
25003   2   3   1   9   1   1   3   8   3   7
25004   3   4   2   8   4   8   1   9   2  11
25005   4   9   4   6   3   6   4  12   4   5
25006   3   8   3   5   4  11   2   2   1  13
25007   1   8   4   5   3  11   3   2   2  13
25008   4  12   3   5   2   1   2   7   4   6
25009   1   1   1   3   1   7   1   2   4   2

[25010 rows x 10 columns]

In [8]:
# checking the size of Feature Matix X:

print(X.shape)

(25010, 10)

In [9]:
from sklearn.tree import DecisionTreeClassifier

In [10]:
# select a Series of labels (the last column) from the DataFrame
y = df['hand']

# checking the label vector by printing every 10 values
y[::10]

0        0
10       0
20       1
30       0
40       0
50       1
60       0
70       0
80       0
90       1
100      1
110      0
120      1
130      0
140      1
150      0
160      6
170      0
180      2
190      0
200      0
210      1
220      0
230      0
240      0
250      0
260      1
270      0
280      0
290      1
        ..
24710    1
24720    2
24730    1
24740    0
24750    1
24760    0
24770    0
24780    0
24790    0
24800    1
24810    0
24820    1
24830    0
24840    0
24850    1
24860    1
24870    2
24880    1
24890    0
24900    2
24910    0
24920    1
24930    0
24940    0
24950    1
24960    0
24970    0
24980    0
24990    0
25000    0
Name: hand, dtype: int64

In [11]:
my_decisiontree = DecisionTreeClassifier()

In [12]:
my_decisiontree.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [13]:
dfnew = pd.DataFrame()


dfnew = pd.read_csv('/Users/cherylmariajose/Desktop/cs4661/project/test.csv')

In [14]:
dfnew

             id  S1  C1  S2  C2  S3  C3  S4  C4  S5  C5
0             1   1  10   2   2   3   3   3   8   1   1
1             2   2  13   3   5   3   7   4   6   1   4
2             3   1   3   1  11   2   8   2   1   2   4
3             4   1   6   3   3   4   7   1   8   3  11
4             5   2  10   3   4   1   6   2  12   2   6
5             6   1   4   3  10   2  11   2   6   1   7
6             7   1  10   3   8   1   4   3  11   3   9
7             8   2  11   3   8   1   1   1  11   2   3
8             9   3   4   1   1   1   3   3   5   3   6
9            10   3  12   2   1   1   3   1   2   3  10
10           11   1   7   3   1   4   8   4  10   3  11
11           12   2   3   2  11   3   9   1  10   2   5
12           13   1   4   2  13   4   6   4   8   4   5
13           14   4   7   4   2   3   3   1   4   1   1
14           15   4   8   3  10   4  11   3   5   1  12
15           16   4  11   1  10   1   3   1   2   4   5
16           17   1   8   3   2   4   4   2   3   3   4
17           18   3   7   1   6   1   4   3  12   3   6
18           19   2   4   1   1   1   9   3   1   2  13
19           20   2   8   1  13   3   2   4   1   4   9
20           21   2   3   1  10   4  12   3  10   2   8
21           22   1   2   3   6   4   7   1   6   3   8
22           23   1   6   1   3   2   2   1   9   4   5
23           24   2   1   4   8   3  11   3   1   2  13
24           25   4   3   4   8   1   9   1   7   4   4
25           26   2  13   4   4   1  12   2   5   3  12
26           27   1   4   4   4   1   5   3   5   2   2
27           28   2  13   3  13   1   2   1   9   1   1
28           29   1   2   3  10   4   8   3   9   2  10
29           30   1   7   1   3   3   8   1   1   2   5
...         ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
999970   999971   2   7   1   7   3   8   2  11   4  10
999971   999972   1  13   4   2   2  12   3   8   4   5
999972   999973   4   8   1   6   3  12   3   5   4  11
999973   999974   1  11   3   6   4   9   3  11   1   8
999974   999975   3  11   3  10   4  12   4   8   4   9
999975   999976   1  11   3   1   1  10   4  10   2   6
999976   999977   1   2   1  13   3  11   2  11   3   8
999977   999978   4   8   4  11   1   9   2   7   3   8
999978   999979   3  12   3   2   1  12   2   9   2   5
999979   999980   3   9   3   2   4  11   3   7   4  10
999980   999981   4   3   2  11   1   1   4   2   2  13
999981   999982   2  13   2   2   4  10   4  12   4   7
999982   999983   4   6   1  11   3   7   4   9   1   4
999983   999984   4   6   4   8   1   9   3   5   1   4
999984   999985   2  13   1   9   3   1   1   4   3  10
999985   999986   3   8   1   3   1  11   1   5   1  12
999986   999987   2   6   4   3   1   1   4   7   4   9
999987   999988   3   2   4   6   4   2   3  13   2  13
999988   999989   1   1   1   5   3   4   2   1   4   9
999989   999990   1   8   2   9   1   2   3   8   3  11
999990   999991   1   5   2  13   4  10   4   2   4  12
999991   999992   4   4   4   1   3   1   2   1   3  12
999992   999993   2  11   1  13   4  13   3   1   4   1
999993   999994   2   7   3   5   3   3   1   6   1   3
999994   999995   2   7   4  13   4   5   2   2   1   5
999995   999996   2   8   3   4   1  13   3   8   2   5
999996   999997   2   8   2   7   4  11   4   8   3   6
999997   999998   1   7   1   8   1   5   2   9   2   5
999998   999999   1   1   2   7   2  13   2   5   3  10
999999  1000000   2   2   3   3   1   3   4   4   3  11

[1000000 rows x 11 columns]

In [17]:
# Creating the Feature Matrix for iris dataset:

# create a python list of feature names that would like to pick from the dataset:
fc = ['S1','C1','S2','C2','S3','C3','S4','C4','S5','C5']

# use the above list to select the features from the original DataFrame
X_Testing = dfnew[fc]  

# print the first 5 rows
X_Testing

        S1  C1  S2  C2  S3  C3  S4  C4  S5  C5
0        1  10   2   2   3   3   3   8   1   1
1        2  13   3   5   3   7   4   6   1   4
2        1   3   1  11   2   8   2   1   2   4
3        1   6   3   3   4   7   1   8   3  11
4        2  10   3   4   1   6   2  12   2   6
5        1   4   3  10   2  11   2   6   1   7
6        1  10   3   8   1   4   3  11   3   9
7        2  11   3   8   1   1   1  11   2   3
8        3   4   1   1   1   3   3   5   3   6
9        3  12   2   1   1   3   1   2   3  10
10       1   7   3   1   4   8   4  10   3  11
11       2   3   2  11   3   9   1  10   2   5
12       1   4   2  13   4   6   4   8   4   5
13       4   7   4   2   3   3   1   4   1   1
14       4   8   3  10   4  11   3   5   1  12
15       4  11   1  10   1   3   1   2   4   5
16       1   8   3   2   4   4   2   3   3   4
17       3   7   1   6   1   4   3  12   3   6
18       2   4   1   1   1   9   3   1   2  13
19       2   8   1  13   3   2   4   1   4   9
20       2   3   1  10   4  12   3  10   2   8
21       1   2   3   6   4   7   1   6   3   8
22       1   6   1   3   2   2   1   9   4   5
23       2   1   4   8   3  11   3   1   2  13
24       4   3   4   8   1   9   1   7   4   4
25       2  13   4   4   1  12   2   5   3  12
26       1   4   4   4   1   5   3   5   2   2
27       2  13   3  13   1   2   1   9   1   1
28       1   2   3  10   4   8   3   9   2  10
29       1   7   1   3   3   8   1   1   2   5
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
999970   2   7   1   7   3   8   2  11   4  10
999971   1  13   4   2   2  12   3   8   4   5
999972   4   8   1   6   3  12   3   5   4  11
999973   1  11   3   6   4   9   3  11   1   8
999974   3  11   3  10   4  12   4   8   4   9
999975   1  11   3   1   1  10   4  10   2   6
999976   1   2   1  13   3  11   2  11   3   8
999977   4   8   4  11   1   9   2   7   3   8
999978   3  12   3   2   1  12   2   9   2   5
999979   3   9   3   2   4  11   3   7   4  10
999980   4   3   2  11   1   1   4   2   2  13
999981   2  13   2   2   4  10   4  12   4   7
999982   4   6   1  11   3   7   4   9   1   4
999983   4   6   4   8   1   9   3   5   1   4
999984   2  13   1   9   3   1   1   4   3  10
999985   3   8   1   3   1  11   1   5   1  12
999986   2   6   4   3   1   1   4   7   4   9
999987   3   2   4   6   4   2   3  13   2  13
999988   1   1   1   5   3   4   2   1   4   9
999989   1   8   2   9   1   2   3   8   3  11
999990   1   5   2  13   4  10   4   2   4  12
999991   4   4   4   1   3   1   2   1   3  12
999992   2  11   1  13   4  13   3   1   4   1
999993   2   7   3   5   3   3   1   6   1   3
999994   2   7   4  13   4   5   2   2   1   5
999995   2   8   3   4   1  13   3   8   2   5
999996   2   8   2   7   4  11   4   8   3   6
999997   1   7   1   8   1   5   2   9   2   5
999998   1   1   2   7   2  13   2   5   3  10
999999   2   2   3   3   1   3   4   4   3  11

[1000000 rows x 10 columns]

In [18]:
y_predict_dt = my_decisiontree.predict(X_Testing)

In [23]:
print(y_predict_dt)

# checking the label vector by printing every 10 values
y_predict_dt[::1]

[0 0 0 ..., 0 1 1]

array([0, 0, 0, ..., 0, 1, 1])